'''
The following program loads in all of the generated spectral features for the soundfiles and generates vectors for each sound file. 
'''
import pandas as pd
from pandas import DataFrame
import re
import torch
from torch import Tensor
import json
from pathlib import Path
import os
import subprocess
    
    
    
def extract_number(filename: str):
    '''
    helper function extracts a number from the filename
    '''
    p = re.compile(r'\d')
    return int("".join(p.findall(filename)))
    
    
def clean_tables(df_dict):
    '''
    drops all the nans from table, sorts them first by their file name index, then by their syllable location
    '''
    key_list = ['syllable_2', 'syllable_3', 'syllable_4']
    key_list2 = ['train', 'test', 'dev']
    for key in key_list:
        for key2 in key_list2:
            df_list = df_dict[key][key2]
            new_list = []
            for dataframe in df_list:
                dataframe.dropna(inplace=True)
                dataframe_key = [extract_number(string) for string in dataframe['fileName']]
                dataframe['key'] = dataframe_key
                dataframe.sort_values(by=['key', 'name'], inplace=True)
                dataframe = set_index(dataframe)
                new_list.append(dataframe.drop(columns=['key', 'fileName', 'name']))
            df_dict[key][key2] = new_list
    return df_dict
    
def set_index(dataframe: DataFrame):
	'''
	feature dataframes will have their indices generated from filename since, this corresponds to the set over which they were generated
	'''
	pattern = re.compile(r'\d+')
	index = [pattern.search(s).group() for s in dataframe['fileName']]
	dataframe['index'] = index
	return dataframe.set_index('index')
	
   
				
def collect_word(df: DataFrame, i: int):
	'''
	the dataframe contains exactly one word with this index, however, since feature data is generated by syllables, we will have more than one row with such an index. this
	function filters those rows and returns them as a sequence of vectors. 
	'''	
	word_features = df[df.index == i]
	features = word_features.astype('float32').to_numpy().tolist()
	print('word features generated', features)
	return features
    
def write_spectral_features(df_dict: dict):
	'''
	for each feature, it generates the list of words that are represented by that feature. 
	input shape: dict[str:dict[str:list]]
	output shape: [f1,..., fn] where each fi = [w1, ..., wm]
	'''
	new_dict = {'syllable_2':{}, 'syllable_3':{}, 'syllable_4':{}}
	clean_dict = clean_tables(df_dict)
	batches= ['train', 'test', 'dev']
	syllables = ['syllable_2', 'syllable_3', 'syllable_4']
	for batch in batches:
		for syllable in syllables:
			new_dict[syllable][batch] = {}
			feature_list = clean_dict[syllable][batch]
			for f, feature_df in enumerate(feature_list):
				new_dict[syllable][batch][f] = {}
				for i in feature_df.index:
					print('saving word features at', syllable, batch, i)
					new_dict[syllable][batch][f][i] = collect_word(feature_df, i)
	return new_dict
	
def write_csvs():
	'''
	the feature tables are currently in an inconvenient txt formant. they need to be written to csv files so that pandas code can work with them.
	'''
	classe = ['data_2', 'data_3', 'data_4']
	batch = ['train', 'test', 'dev']
	type = ['formant', 'pitch', 'intensity']
	
	for c in classe:
		for b in batch:
			for t in type:
				path = Path(f'data/{c}/{b}/features/{t}/dur_{t}.txt')
				string = ''
				with path.open(mode='r') as f:
					string = f.read()
				csv = re.sub(r'\t', ',', string)
				subprocess.run(['rm', f'data/{c}/{b}/features/{t}/dur_{t}.csv' ])
				newpath = Path(f'data/{c}/{b}/features/{t}/dur_{t}.csv')
				with newpath.open(mode='w') as f:
					f.write(csv)

def prepare_data():
	'''
	main function which prepares all of the spectral features and writes them as a json dictionary to the current directory.
	'''
	write_csvs()
	
	print('reading in feature tables')
	train_formant_2_syll_table = pd.read_csv('data/data_2/train/features/formant/dur_formant.csv')
	train_duration_2_syll_table = pd.concat([train_formant_2_syll_table['duration'], train_formant_2_syll_table['fileName'], train_formant_2_syll_table['name']], axis=1)
	train_formant_2_syll_table.drop(columns='duration', inplace=True)
	
	train_intensity_2_syll_table = pd.read_csv('data/data_2/train/features/intensity/dur_intensity.csv')
	train_intensity_2_syll_table.drop(columns=['duration','intensity1', 'intensity10'], inplace=True)
	
	train_pitch_2_syll_table = pd.read_csv('data/data_2/train/features/pitch/dur_pitch.csv')
	train_pitch_2_syll_table.drop(columns='duration', inplace=True)

	dev_formant_2_syll_table = pd.read_csv('data/data_2/dev/features/formant/dur_formant.csv')
	dev_duration_2_syll_table = pd.concat([dev_formant_2_syll_table['duration'], dev_formant_2_syll_table['fileName'],dev_formant_2_syll_table['name']], axis=1)
	dev_formant_2_syll_table.drop(columns='duration', inplace=True)
	
	dev_intensity_2_syll_table = pd.read_csv('data/data_2/dev/features/intensity/dur_intensity.csv')
	dev_intensity_2_syll_table.drop(columns=['duration', 'intensity1', 'intensity10'], inplace=True)
	
	dev_pitch_2_syll_table = pd.read_csv('data/data_2/dev/features/pitch/dur_pitch.csv')
	dev_pitch_2_syll_table.drop(columns='duration', inplace=True)

	test_formant_2_syll_table = pd.read_csv('data/data_2/test/features/formant/dur_formant.csv')
	test_duration_2_syll_table = pd.concat([test_formant_2_syll_table['duration'], test_formant_2_syll_table['fileName'],test_formant_2_syll_table['name']], axis=1)
	test_formant_2_syll_table.drop(columns='duration', inplace=True)
	
	test_intensity_2_syll_table = pd.read_csv('data/data_2/test/features/intensity/dur_intensity.csv')
	test_intensity_2_syll_table.drop(columns=['duration', 'intensity1', 'intensity10'], inplace=True)
	
	test_pitch_2_syll_table = pd.read_csv('data/data_2/test/features/pitch/dur_pitch.csv')
	test_pitch_2_syll_table.drop(columns='duration', inplace=True)
	
	train_formant_3_syll_table = pd.read_csv('data/data_3/train/features/formant/dur_formant.csv')
	train_duration_3_syll_table = pd.concat([train_formant_3_syll_table['duration'], train_formant_3_syll_table['fileName'], train_formant_3_syll_table['name']], axis=1)
	train_formant_3_syll_table.drop(columns='duration', inplace=True)
	
	train_intensity_3_syll_table = pd.read_csv('data/data_3/train/features/intensity/dur_intensity.csv')
	train_intensity_3_syll_table.drop(columns=['duration', 'intensity1', 'intensity10'], inplace=True)
	
	train_pitch_3_syll_table = pd.read_csv('data/data_3/train/features/pitch/dur_pitch.csv')
	train_pitch_3_syll_table.drop(columns='duration', inplace=True)

	dev_formant_3_syll_table = pd.read_csv('data/data_3/dev/features/formant/dur_formant.csv')
	dev_duration_3_syll_table = pd.concat([dev_formant_3_syll_table['duration'],dev_formant_3_syll_table['fileName'],dev_formant_3_syll_table['name']], axis = 1)
	dev_formant_3_syll_table.drop(columns='duration', inplace=True)
	
	dev_intensity_3_syll_table = pd.read_csv('data/data_3/dev/features/intensity/dur_intensity.csv')
	dev_intensity_3_syll_table.drop(columns=['duration','intensity1', 'intensity10'], inplace=True)
	
	dev_pitch_3_syll_table = pd.read_csv('data/data_3/dev/features/pitch/dur_pitch.csv')
	dev_pitch_3_syll_table.drop(columns='duration', inplace=True)
	
	test_formant_3_syll_table = pd.read_csv('data/data_3/test/features/formant/dur_formant.csv')
	test_duration_3_syll_table = pd.concat([test_formant_3_syll_table['duration'],test_formant_3_syll_table['fileName'],test_formant_3_syll_table['name']], axis=1)
	test_formant_3_syll_table.drop(columns='duration', inplace=True)
	
	test_intensity_3_syll_table = pd.read_csv('data/data_3/test/features/intensity/dur_intensity.csv')
	test_intensity_3_syll_table.drop(columns=['duration','intensity1', 'intensity10'], inplace=True)
	
	test_pitch_3_syll_table = pd.read_csv('data/data_3/test/features/pitch/dur_pitch.csv')
	test_pitch_3_syll_table.drop(columns='duration', inplace=True)
	
	train_formant_4_syll_table = pd.read_csv('data/data_4/train/features/formant/dur_formant.csv')
	train_duration_4_syll_table = pd.concat([train_formant_4_syll_table['duration'],train_formant_4_syll_table['fileName'],train_formant_4_syll_table['name']], axis=1)
	train_formant_4_syll_table.drop(columns='duration', inplace=True)
	
	train_intensity_4_syll_table = pd.read_csv('data/data_4/train/features/intensity/dur_intensity.csv')
	train_intensity_4_syll_table.drop(columns=['duration','intensity1', 'intensity10'], inplace=True)
	
	train_pitch_4_syll_table = pd.read_csv('data/data_4/train/features/pitch/dur_pitch.csv')
	train_pitch_4_syll_table.drop(columns='duration', inplace=True)

	dev_formant_4_syll_table = pd.read_csv('data/data_4/dev/features/formant/dur_formant.csv')
	dev_duration_4_syll_table = pd.concat([dev_formant_4_syll_table['duration'],dev_formant_4_syll_table['fileName'],dev_formant_4_syll_table['name']], axis=1)
	dev_formant_4_syll_table.drop(columns='duration', inplace=True)
	
	dev_intensity_4_syll_table = pd.read_csv('data/data_4/dev/features/intensity/dur_intensity.csv')
	dev_intensity_4_syll_table.drop(columns=['duration','intensity1', 'intensity10'], inplace=True)
	
	dev_pitch_4_syll_table = pd.read_csv('data/data_4/dev/features/pitch/dur_pitch.csv')
	dev_pitch_4_syll_table.drop(columns='duration', inplace=True)
	
	test_formant_4_syll_table = pd.read_csv('data/data_4/test/features/formant/dur_formant.csv')
	test_duration_4_syll_table = pd.concat([test_formant_4_syll_table['duration'],test_formant_4_syll_table['fileName'],test_formant_4_syll_table['name']], axis=1)
	test_formant_4_syll_table.drop(columns='duration', inplace=True)
	
	test_intensity_4_syll_table = pd.read_csv('data/data_4/test/features/intensity/dur_intensity.csv')
	test_intensity_4_syll_table.drop(columns=['duration','intensity1', 'intensity10'], inplace=True)
	
	test_pitch_4_syll_table = pd.read_csv('data/data_4/test/features/pitch/dur_pitch.csv')
	test_pitch_4_syll_table.drop(columns='duration', inplace=True)
	
	df_dict = {
          	 'syllable_2': {
	 'train':[train_duration_2_syll_table, train_formant_2_syll_table, train_intensity_2_syll_table, train_pitch_2_syll_table],
	 'dev':[dev_duration_2_syll_table, dev_formant_2_syll_table, dev_intensity_2_syll_table, dev_pitch_2_syll_table],
	 'test':[test_duration_2_syll_table, test_formant_2_syll_table, test_intensity_2_syll_table, test_pitch_2_syll_table]
	 },
            	'syllable_3':{
	'train':[train_duration_3_syll_table, train_formant_3_syll_table, train_intensity_3_syll_table, train_pitch_3_syll_table],
	'dev':[dev_duration_3_syll_table, dev_formant_3_syll_table, dev_intensity_3_syll_table, dev_pitch_3_syll_table],
	'test':[test_duration_3_syll_table, test_formant_3_syll_table, test_intensity_3_syll_table, test_pitch_3_syll_table]
	},
            	'syllable_4':{
	'train':[train_duration_4_syll_table, train_formant_4_syll_table, train_intensity_4_syll_table, train_pitch_4_syll_table],
	'dev':[dev_duration_4_syll_table, dev_formant_4_syll_table, dev_intensity_4_syll_table, dev_pitch_4_syll_table],
	'test':[test_duration_4_syll_table, test_formant_4_syll_table, test_intensity_4_syll_table, test_pitch_4_syll_table]
	}
	}
		
	return write_spectral_features(df_dict)
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	