'''
The following program loads in all of the generated spectral features for the soundfiles and generates vectors for each sound file. 
'''
import pandas as pd
from pandas import DataFrame
import numpy as np
import re
import torch
from torch import Tensor
import json
from pathlib import Path
import os
import subprocess
    
    
    
def extract_number(filename: str):
    '''
    helper function extracts a number from the filename
    '''
    p = re.compile(r'\d')
    return int("".join(p.findall(filename)))
    
    
def clean_tables():
	'''
	drops all the nans from table, sorts them first by their file name index, then by their syllable location
	'''
	classe = ['data_2', 'data_3', 'data_4']
	batch = ['train', 'test', 'dev']
	type = ['formant', 'pitch']
	max = 0
	
	dictionary = {
			'train':{ 'data_2': {}, 'data_3':{}, 'data_4':{}
		}, 
			'test':{'data_2':{}, 'data_3':{}, 'data_4':{}
		}, 
			'dev':{'data_2':{}, 'data_3':{}, 'data_4':{}
		}
		}
	
	for i, s in enumerate(classe):
		syll = i + 2
		for b in batch:
			pathsource = Path(f'data/{s}/{b}/{b}.csv')
			sourcetable = pd.read_csv(pathsource)
			sourcetable = sourcetable.set_index('Unnamed: 0')
			print('reading from table', pathsource)
			for j in sourcetable.index:
				dictionary[b][s][j] = {}
				for k in range(syll):
					dictionary[b][s][j][k] = {}
					for t in type:
						pathtarget = Path(f'data/{s}/{b}/features/{t}/file_{j}_syll{k + 1}.csv')
						print('generating from file', pathtarget)
						if pathtarget.exists():
							targettable = pd.read_csv(pathtarget)
							for c in targettable.columns:
								if c in {'time(s)', 'intensity'}:
									column = targettable[c]
									column = column.replace('-undefined--', np.nan)
									column = column.dropna()
									column = column.astype('float32')
									dictionary[b][s][j][k][c] = column.to_numpy().tolist()
									print('added', c)
									if len(column) > max:
										max = len(targettable[c])
									print(len(column))
									continue
								if c in {'none', 'Time'}:
									print('ignored', c)
									continue
								column = targettable[c]
								column = column.replace('--undefined--', np.nan)
								column = column.dropna()
								column = column.astype('float32')
								if len(column) == 1:
									#column = [0]
									dictionary[b][s][j][k][c] = column.to_numpy().tolist()
									continue
								mean = column.mean()
								std = column.std()
								normal = column
								dictionary[b][s][j][k][c] = normal.to_numpy().tolist()
								if len(normal) > max:
									max = len(normal)
								print('added', c)
								print(len(normal))
						else:
							print('warning', pathtarget, 'does not exist')	
	return max, dictionary
    
def set_index(dataframe: DataFrame):
	'''
	feature dataframes will have their indices generated from filename since, this corresponds to the set over which they were generated
	'''
	pattern = re.compile(r'\d+')
	index = [pattern.search(s).group() for s in dataframe['fileName']]
	dataframe['index'] = index
	return dataframe.set_index('index')
	
   
				
def collect_word(df: DataFrame, i: int):
	'''
	the dataframe contains exactly one word with this index, however, since feature data is generated by syllables, we will have more than one row with such an index. this
	function filters those rows and returns them as a sequence of vectors. 
	'''	
	word_features = df[df.index == i]
	features = word_features.astype('float32').to_numpy().tolist()
	print('word features generated', features)
	return features
    
def write_spectral_features(df_dict: dict):
	'''
	for each feature, it generates the list of words that are represented by that feature. 
	input shape: dict[str:dict[str:list]]
	output shape: [f1,..., fn] where each fi = [w1, ..., wm]
	'''
	classe = ['data_2', 'data_3', 'data_4']
	batch = ['train', 'test', 'dev']
	type = ['formant', 'pitch']
	
	new_dict = {'syllable_2':{}, 'syllable_3':{}, 'syllable_4':{}}
	clean_dict = clean_tables()
	batches= ['train', 'test', 'dev']
	syllables = ['syllable_2', 'syllable_3', 'syllable_4']
	for batch in batches:
		for syllable in syllables:
			new_dict[syllable][batch] = {}
			feature_list = clean_dict[syllable][batch]
			for f, feature_df in enumerate(feature_list):
				new_dict[syllable][batch][f] = {}
				for i in feature_df.index:
					print('saving word features at', syllable, batch, i)
					new_dict[syllable][batch][f][i] = collect_word(feature_df, i)
	return new_dict
	
def write_csvs():
	'''
	the feature tables are currently in an inconvenient txt formant. they need to be written to csv files so that pandas code can work with them.
	'''
	classe = ['data_2', 'data_3', 'data_4']
	batch = ['train', 'test', 'dev']
	type = ['formant', 'pitch', 'intensity']
	
	for c in classe:
		for b in batch:
			for t in type:
				path = Path(f'data/{c}/{b}/features/{t}/dur_{t}.txt')
				string = ''
				with path.open(mode='r') as f:
					string = f.read()
				csv = re.sub(r'\t', ',', string)
				subprocess.run(['rm', f'data/{c}/{b}/features/{t}/dur_{t}.csv' ])
				newpath = Path(f'data/{c}/{b}/features/{t}/dur_{t}.csv')
				with newpath.open(mode='w') as f:
					f.write(csv)

def prepare_data():
	'''
	main function which prepares all of the spectral features and writes them as a json dictionary to the current directory.
	'''
	print('preparing feature data')
	max, dictionary = clean_tables()
	print('prepared feature data')
	return max, dictionary
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	